on: [push, pull_request]
  
jobs:
  build-clinicarrivals:
    runs-on: windows-latest
     
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
    
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Checkout source code
      uses: actions/checkout@v2.0.0
  
    - name: Restore packages
      run: nuget restore
    
    - name: Build ClinicArrivals.Server
      run: dotnet msbuild ClinicArrivals.sln
