name: Publish release

on: push
#   release:
#     types: created      
  
  
jobs:
  publish-clinicarrivals:
    runs-on: windows-latest
    env:
      buildtype: Release
     
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
    
    - name: Setup nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Setup msbuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Checkout source code
      uses: actions/checkout@v2.0.0
  
    - name: Restore packages
      run: nuget restore
    
    - name: Build ClinicArrivals
      run: msbuild /p:Configuration=${{env.buildtype}} -maxcpucount:2 ClinicArrivals.sln
    
    - name: Update nuspec
      env:
#         TAG_NAME: ${{github.event.release.tag_name}}
        TAG_NAME: "0.0.1"
        WORKSPACE: ${{runner.workspace}}
      run: |
        $SQUIRRELWIN = "$env:WORKSPACE\squirrel-packaging-prep"
        $SQUIRRELWINBIN = "$SQUIRRELWIN\lib\net45\"
        if (-not $(Test-Path "$SQUIRRELWINBIN")) {
          New-Item "$SQUIRRELWINBIN" -ItemType "directory"
        }
        
        Move-Item $env:WORKSPACE\ClinicArrivals\ClinicArrivals\bin\$env:buildtype\* $SQUIRRELWINBIN
        Remove-Item $env:WORKSPACE\ClinicArrivals\ClinicArrivals\bin\$env:buildtype\* -include *.pdb, *.vshost.*
        
        $Script:NuSpec = "$env:WORKSPACE\ClinicArrivals.nuspec"
        nuget pack "$Script:NuSpec" -Version "$env:TAG_NAME" -BasePath $SQUIRRELWIN -OutputDirectory $SQUIRRELWIN

        TREE /F

      shell: powershell
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ClinicArrivals
        path: ${{runner.workspace}}\ClinicArrivals\ClinicArrivals\bin\${{env.buildtype}}
            
    - name: Create release archive
      if: "false"
      run: 7z a ClinicArrivals-${{github.event.release.tag_name}}-win.zip ${{runner.workspace}}\ClinicArrivals\ClinicArrivals\bin\${{env.buildtype}}\*

    - name: Upload archive to release
      uses: actions/upload-release-asset@v1.0.1
      if: "false"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_name: ClinicArrivals-${{github.event.release.tag_name}}-win.zip
        asset_path: ClinicArrivals-${{github.event.release.tag_name}}-win.zip
        asset_content_type: application/zip
