name: Publish release

on: push
#   release:
#     types: created      
  
  
jobs:
  publish-clinicarrivals:
    runs-on: windows-latest
    env:
      buildtype: Release
     
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
    
    - name: Setup nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Setup msbuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Checkout source code
      uses: actions/checkout@v2.0.0
  
    - name: Restore packages
      run: nuget restore
    
    - name: Compile ClinicArrivals
      run: msbuild /p:Configuration=${{env.buildtype}} -maxcpucount:2 ClinicArrivals.sln
    
    - name: Build installer
      env:
#         TAG_NAME: ${{github.event.release.tag_name}}
        TAG_NAME: "0.0.1"
        WORKSPACE: ${{runner.workspace}}
      run: |
        $SQUIRRELWIN = "$env:WORKSPACE\squirrel-packaging-prep"
        $SQUIRRELWINBIN = "$SQUIRRELWIN\lib\net45\"
        $RELEASEDIR = "$env:WORKSPACE\finished-installer"
        if (-not $(Test-Path "$SQUIRRELWINBIN")) {
          New-Item "$SQUIRRELWINBIN" -ItemType "directory"
        }
        
        Move-Item $env:WORKSPACE\ClinicArrivals\ClinicArrivals\bin\$env:buildtype\* $SQUIRRELWINBIN
        Remove-Item $env:WORKSPACE\ClinicArrivals\ClinicArrivals\bin\$env:buildtype\* -include *.pdb, *.vshost.*
        Move-Item $env:WORKSPACE\ClinicArrivals\ClinicArrivals.png $SQUIRRELWIN
        
        $Script:NuSpec = "$env:WORKSPACE\ClinicArrivals\ClinicArrivals.nuspec"
                
        nuget pack "$Script:NuSpec" -Version "$env:TAG_NAME" -BasePath $SQUIRRELWIN -OutputDirectory $SQUIRRELWIN

        $Script:NupkgPath = "$SQUIRRELWIN\ClinicArrivals.$env:TAG_NAME.nupkg"
        
        if (-not (Test-Path -Path $Script:NupkgPath -PathType Leaf)) {
          Write-Output "ERROR: nupkg doesn't exist as expected! Build aborted."
          exit 1
        }  
               
        nuget install squirrel.windows -ExcludeVersion
       
        # fails silently if the nupkg file is not found
        .\squirrel.windows\tools\Squirrel --releasify $Script:NupkgPath --releaseDir $RELEASEDIR --no-msi --setupIcon $env:workspace\ClinicArrivals\ClinicArrivals\ClinicArrivals.ico        
        
        TREE /F $RELEASEDIR
        if (-not (Test-Path -Path "$RELEASEDIR\Setup.exe" -PathType Leaf)) {
          Write-Output "=== ERROR: Squirrel failed to generate the installer! Build aborted. Squirrel log is:"
          Get-Content -Path .\squirrel.windows\tools\SquirrelSetup.log
          exit 1
        }
        
        echo "::set-env name=RELEASEDIR::$RELEASEDIR"

      shell: powershell
    
    - name: Upload installer
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ClinicArrivals-installer
        path: ${{env.RELEASEDIR}}
            
    - name: Create release archive
      if: "false"
      run: 7z a ClinicArrivals-${{github.event.release.tag_name}}-win.zip ${{runner.workspace}}\ClinicArrivals\ClinicArrivals\bin\${{env.buildtype}}\*

    - name: Upload archive to release
      uses: actions/upload-release-asset@v1.0.1
      if: "false"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_name: ClinicArrivals-${{github.event.release.tag_name}}-win.zip
        asset_path: ClinicArrivals-${{github.event.release.tag_name}}-win.zip
        asset_content_type: application/zip
